<nav class="navbar navbar-expand-lg sticky-top sticky_header">
    <div class="container"><a class="navbar-brand" title="Iron Rods" href=""><img src="<?php echo $this->getViewFileUrl('images/logo.png'); ?>" alt="Iron Rods"></a> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNavbar" aria-controls="topNavbar" aria-expanded="false" aria-label="Toggle navigation"></button>
        <div id="topNavbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link active" title="Home" href="">Home</a></li>
                <li class="nav-item"><a class="nav-link" title="Collections" href="collections.html">Collections</a></li>
                <li class="nav-item"><a class="nav-link" title="Help Center" href="help-center.html">Help Center</a></li>
                <li class="nav-item"><a class="nav-link" title="About" href="about-us">About</a></li>
                <li class="nav-item"><a class="nav-link" title="Contact" href="contact">Contact</a></li>
            </ul>
            <form class="form-inline my-2 my-lg-0 py-2 py-lg-0"><a class="btn_blue" title="Create Account" href="customer/account/create">Create Account</a> <a class="btn_blue ml-2" title="Sign In" href="customer/account/login">Sign In</a></form></div>
    </div>
</nav>